layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
    scope:
      path: "assets/img"
    values:
      img: "true"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects: study, pfp, bloom
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: guijansen
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 4984392
  # telegram: your_username
  twitter: guilhermejansen
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: 3D Printing
    web_url: https://en.wikipedia.org/wiki/3D_printing
    #source: https://clipground.com/images/benchy-clipart-4.jpg
    image_url: assets/img/benchy-clipart-4.jpg

  - name: Arduino
    web_url: https://github.com/topics/arduino
    #source: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/arduino/arduino.png
    image_url: assets/img/arduino.png

  - name: Amazon Web Services
    web_url: https://github.com/topics/aws
    #source: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png
    image_url: assets/img/aws.png

  - name: Bitcoin
    web_url: https://github.com/topics/bitcoin
    #source: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/bitcoin/bitcoin.png
    image_url: assets/img/bitcoin.png

  - name: Celluar Automata
    web_url: https://en.wikipedia.org/wiki/Cellular_automaton
    #source: https://avatars2.githubusercontent.com/u/1459428?s=400&v=4
    image_url: assets/img/1459428.png

  - name: Cybernetics
    web_url: https://github.com/topics/cybernetics
    #source: https://png.pngtree.com/svg/20161107/242c83499c.svg
    image_url: assets/img/242c83499c.svg

  - name: Docker
    web_url: https://github.com/topics/docker
    #source: https://events.docker.com/android-chrome-192x192.png
    image_url: assets/img/android-chrome-192x192.png

  - name: Git
    web_url: https://github.com/topics/git
    #source: https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png
    image_url: assets/img/Git-Icon-1788C.png

  - name: Java
    web_url: https://github.com/topics/java
    #source: https://www.softexia.com/wp-content/uploads/2017/04/Java-logo.png
    image_url: assets/img/Java-logo.png

  - name: Jupyter Notebook
    web_url: https://github.com/topics/jupyter-notebook
    #source: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/jupyter-notebook/jupyter-notebook.png
    image_url: assets/img/jupyter-notebook.png

  - name: LaTeX
    web_url: https://github.com/topics/latex
    #source: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/latex/latex.png
    image_url: assets/img/latex.png

  - name: Maven
    web_url: https://github.com/topics/maven
    #source: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/maven/maven.png
    image_url: assets/img/maven.png

  - name: Open Source Software
    web_url: https://en.wikipedia.org/wiki/Open-source_software
    #source: https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Open_Source_Initiative_keyhole.svg/1200px-Open_Source_Initiative_keyhole.svg.png
    image_url: assets/img/Open_Source_Initiative_keyhole.svg.png

  - name: Open Source Hardware
    web_url: https://en.wikipedia.org/wiki/Open-source_hardware
    #source: https://www.simracingcoach.com/wp-content/uploads/2015/04/logo_hardware.png
    image_url: assets/img/logo_hardware.png

  - name: Linux
    web_url: https://github.com/topics/linux
    #source: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png
    image_url: assets/img/linux.png

  - name: Processing
    web_url: https://en.wikipedia.org/wiki/Processing_(programming_language)
    #source: https://github.com/processing/processing/raw/master/build/shared/lib/icons/pde-128.png
    image_url: assets/img/pde-128.png

  - name: Python
    web_url: https://github.com/topics/python
    #source: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png
    image_url: assets/img/python.png

  - name: Raspberry Pi
    web_url: https://github.com/topics/raspberry-pi
    #source: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/raspberry-pi/raspberry-pi.png
    image_url: assets/img/raspberry-pi.png

  - name: Self-Reference
    web_url: https://en.wikipedia.org/wiki/Self-reference
    #source: http://egyptian-gods.org/wp-content/uploads/2011/06/Egyptian-Symbol-Ouroboros-300x300.png
    image_url: assets/img/Egyptian-Symbol-Ouroboros-300x300.png

  - name: Self-Reproducing Automata
    web_url: https://en.wikipedia.org/wiki/Von_Neumann_universal_constructor
    #source: https://cdn.onlinewebfonts.com/svg/img_493802.png
    image_url: assets/img/img_493802.png

  - name: Spring Framework
    web_url: https://github.com/topics/spring-boot
    #source: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/spring-boot/spring-boot.png
    image_url: assets/img/spring-boot.png

  - name: Tensorflow
    web_url: https://github.com/topics/tensorflow
    #source: https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Tensorflow_logo.svg/718px-Tensorflow_logo.svg.png
    image_url: assets/img/Tensorflow_logo.svg.png

  - name: Terraform
    web_url: https://github.com/topics/terraform
    #source: https://icinga.com/wp-content/uploads/2015/06/terraform_logo.png
    image_url: assets/img/terraform_logo.png

  - name: Ubuntu
    web_url: https://github.com/topics/ubuntu
    #source: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/ubuntu/ubuntu.png
    image_url: assets/img/ubuntu.png
